const D=require('../../utils/domain');
Page({
 data:{view:'home',nav:[{id:'home',icon:'⌂',name:'休憩'},{id:'plan',icon:'◇',name:'规划'},{id:'map',icon:'⌖',name:'地图'},{id:'carbon',icon:'◉',name:'碳账户'},{id:'mine',icon:'♙',name:'我的'}],stations:D.stations,services:D.services,extraServices:D.extraServices,facilities:D.facilities,journey:[{step:'出发前',icon:'01',title:'全程规划',desc:'休息与补能一起安排',view:'plan'},{step:'行驶中',icon:'02',title:'疲劳关怀',desc:'记录驾驶时长',view:'plan'},{step:'到站后',icon:'03',title:'安心导航',desc:'无障碍路线优先',view:'map'},{step:'离站后',icon:'04',title:'碳账单',desc:'绿色停留有迹可循',view:'carbon'}],personas:[{icon:'货',title:'货车司机',desc:'车位、淋浴、洗衣与叫醒'},{icon:'亲',title:'家庭亲子',desc:'母婴设施、亲子地图与拥挤提示'},{icon:'助',title:'长者无障碍',desc:'家属代约、大字与平层路线'}],greenCatalog:[{key:'cup',name:'自带水杯',points:5},{key:'plate',name:'光盘行动',points:8},{key:'green',name:'绿电休息',points:10},{key:'walk',name:'步行舒展',points:3}],stationNames:D.stations.map(s=>s.name),serviceNames:D.services.map(s=>s.name),stationIndex:0,serviceIndex:0,consent:false,proxy:false,origin:'',destination:'',feedback:'',facility:null,route:null,routeStations:[],kindIndex:0,kinds:['设施故障','卫生问题','文字呼叫','无障碍协助']},
 onLoad(){this.state=D.restore(wx.getStorageSync('zhizhi-v1'));const dt=new Date(Date.now()+3600000);this.setData({day:[dt.getFullYear(),String(dt.getMonth()+1).padStart(2,'0'),String(dt.getDate()).padStart(2,'0')].join('-'),time:String(dt.getHours()).padStart(2,'0')+':'+String(dt.getMinutes()).padStart(2,'0')});this.refresh();},
 refresh(){const bookings=this.state.bookings.map(b=>({...b,station:D.stations.find(s=>s.id===b.stationId).name,service:D.services.find(s=>s.id===b.serviceId).name,timeText:new Date(b.at).toLocaleString(),statusText:{confirmed:'预约成功',completed:'已完成',cancelled:'已取消',rescheduled:'已改签'}[b.status]}));const completed=bookings.filter(b=>b.status==='completed');const carbon=completed.reduce((a,b)=>a+D.carbon(1.2,D.stations.find(s=>s.id===b.stationId).green).saved,0);const queues=this.state.queues.map(q=>({...q,service:D.extraServices.find(s=>s.id===q.serviceId).name})),serviceRequests=this.state.serviceRequests.map(r=>({...r,service:D.extraServices.find(s=>s.id===r.serviceId).name}));getApp().globalData.incognito=this.state.settings.incognito;this.setData({state:this.state,bookings,queues,serviceRequests,carbon:carbon.toFixed(3),completed:completed.length,pending:bookings.filter(b=>b.status==='confirmed').length,tickets:this.state.tickets,points:this.state.points});if(!this.state.settings.incognito)wx.setStorageSync('zhizhi-v1',this.state);else wx.removeStorageSync('zhizhi-v1');},
 run(fn){try{fn();this.refresh();}catch(e){wx.showToast({title:e.message,icon:'none'});}},
 toast(title){wx.showToast({title,icon:'none'});},
 go(e){this.setData({view:e.currentTarget.dataset.view});wx.pageScrollTo({scrollTop:0,duration:0});},
 book(e){this.setData({view:'book',stationIndex:Number(e.currentTarget.dataset.station||0),serviceIndex:Number(e.currentTarget.dataset.service||0),consent:false});},
 field(e){this.setData({[e.currentTarget.dataset.key]:e.detail.value});},
 check(e){this.setData({[e.currentTarget.dataset.key]:e.detail.value.length>0});},
 submitBooking(){this.run(()=>{D.reserve(this.state,{stationId:D.stations[this.data.stationIndex].id,serviceId:D.services[this.data.serviceIndex].id,at:this.data.day+'T'+this.data.time+':00+08:00',consent:this.data.consent,proxy:this.data.proxy});this.setData({view:'mine'});this.toast('演示预约成功');});},
 cancel(e){wx.showModal({title:'取消本次预约？',content:'取消后预约码失效。',success:r=>{if(r.confirm)this.run(()=>D.cancel(this.state,e.currentTarget.dataset.id));}});},
 complete(e){this.run(()=>{D.complete(this.state,e.currentTarget.dataset.id);this.toast('核销完成，获得20积分');});},
 change(e){const b=this.state.bookings.find(b=>b.id===e.currentTarget.dataset.id),options=D.stations.filter(s=>s.id!==b.stationId);wx.showActionSheet({itemList:options.map(s=>s.name),success:r=>this.run(()=>{D.reschedule(this.state,b.id,options[r.tapIndex].id);this.toast('已改签并更新预约码');})});},
 plan(){this.run(()=>{const route=D.plan({origin:this.data.origin,destination:this.data.destination,avoidBusy:true,quiet:true});this.setData({route,routeStations:route.stations});});},
 favorite(){this.run(()=>{if(!this.data.routeStations.length)throw Error('请先生成路线');if(this.state.favorites.some(f=>f.origin===this.data.origin&&f.destination===this.data.destination))throw Error('已经收藏过该路线');this.state.favorites.push({origin:this.data.origin,destination:this.data.destination});this.toast('路线已收藏');});},
 locate(e){this.setData({facility:D.facilities.find(f=>f.id===e.currentTarget.dataset.id)});},
 scan(){wx.scanCode({onlyFromCamera:false,success:r=>this.identify(r.result),fail:()=>this.toast('未完成扫码，可输入位置码')});},
 identify(code){const match=/^ZZ:s1:([a-z]+)$/.exec(code.trim());if(!match||!D.facilities.some(f=>f.id===match[1]))return this.toast('位置码无效');this.setData({facility:D.facilities.find(f=>f.id===match[1])});this.toast('位置识别成功');},
 manual(){this.identify(this.data.positionCode||'');},
 offline(){this.run(()=>{this.state.offline={saved:Date.now(),facilities:D.facilities};this.toast('地图和预约已保存在本设备');});},
 feedback(){this.run(()=>{D.ticket(this.state,{stationId:D.stations[this.data.stationIndex].id,kind:this.data.kinds[this.data.kindIndex],text:this.data.feedback});this.setData({view:'mine',feedback:''});this.toast('已生成本地演示工单');});},
 progress(e){this.run(()=>D.progress(this.state,e.currentTarget.dataset.id));},
 progressService(e){this.run(()=>D.progressService(this.state,e.currentTarget.dataset.id));},
 redeem(e){this.run(()=>{D.redeem(this.state,e.currentTarget.dataset.name,Number(e.currentTarget.dataset.cost));this.toast('演示兑换成功');});},
 takeQueue(e){this.run(()=>{const q=D.takeQueue(this.state,{stationId:D.stations[this.data.stationIndex].id,serviceId:e.currentTarget.dataset.id});this.toast('取号成功 '+q.number);});},
 cancelQueue(e){this.run(()=>{D.cancelQueue(this.state,e.currentTarget.dataset.id);this.toast('号码已取消');});},
 requestService(e){this.run(()=>{D.requestService(this.state,{stationId:D.stations[this.data.stationIndex].id,serviceId:e.currentTarget.dataset.id,note:''});this.toast('服务已登记');});},
 guard(e){this.run(()=>{const on=D.toggleGuard(this.state,e.currentTarget.dataset.key);this.toast(on?'守护意愿已登记':'守护已关闭');});},
 greenAction(e){this.run(()=>{D.greenAction(this.state,e.currentTarget.dataset.key);this.toast('已记录并获得积分');});},
 toggle(e){this.run(()=>{const key=e.currentTarget.dataset.key;this.state.settings[key]=!this.state.settings[key];});},
 clear(){wx.showModal({title:'删除本设备全部数据？',content:'预约、反馈、收藏及积分将清空，无法恢复。',success:r=>{if(r.confirm){wx.removeStorageSync('zhizhi-v1');this.state=D.initial();this.refresh();this.toast('本地数据已重置');}}});},
 drive(){this.run(()=>{if(this.state.driveStart){const n=Math.floor((Date.now()-this.state.driveStart)/60000);this.state.driveStart=null;this.toast('本段驾驶记录 '+n+' 分钟');}else{this.state.driveStart=Date.now();this.toast('已开始记录，无后台提醒');}});}
});
